# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: cupy
channels:
  - defaults
dependencies:
  - jupyterlab=1.2
  - jupyterhub=1.0
  - dask=2.9
  - distributed=2.9
  - tornado=6.0
  - cupy=6.0
